on: "push"

name: Run the Jest test suite

jobs:
  setupAndTest:
    name: Run all tests & lint the code
    runs-on: ubuntu-latest
    env:
      node-version: '13.10.1'
    steps:
    - uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
    - uses: actions/cache@v2
      name: Cache NPM packages
      id: cache-npm
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
    - uses: actions/setup-node@v1
      with:
        node-version: ${{env.node_version}}
    - name: Set up node CI environment
      run: npm ci
      if: steps.cache-npm.outputs.cache-hit != 'true'
    - name: Jest Test Suite
      run: npm run test
    - name: Lint code
      run: npm run lint
